name: RE Python
on:
  push:
    branches: [ "main" ]
    paths:
      - 'warp.py'
  schedule: #every fuckin 60 minutes
    - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ipaddress
   
    - name: Run script
      run: python warp.py
    - name: Commit and push changes
      run: |          
          git config --global user.email "diana.clk01@gmail.com"
          git config --global user.name "Diana-Cl"
          git config credential.helper store
          git add -A
          git diff --cached --quiet || git commit -m "ⅣⅭ Updated: $(TZ='Asia/Tehran' date '%l:%M %p, +%A, %d %b %Y')"
          git push
          
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
