name: REPy

on:
  push:
    branches: [ "main" ]
    paths:
      - 'warp.py'
  schedule: #every fuckin 60 minutes
    - cron: '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ipaddress
   
    - name: Run script
      run: python warp.py
      
    - name: Commit & Push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git diff --quiet && git diff --staged --quiet || (git commit -m "ⅣⅭ Updated: $(TZ='Asia/Tehran' date '%l:%M %p ,+%A, %d %b %Y')" && git push)
